param(
    [Parameter(Mandatory = $true)]
    [string]$OutFile,
    [string]$PropsFile = ""
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $root

$count = 0
try {
    $raw = (git rev-list --count HEAD 2>$null | Select-Object -Last 1).Trim()
    if ($raw -match '^\d+$') { $count = [int]$raw }
} catch {
    $count = 0
}

$major = [int][Math]::Floor($count / 100)
$minor = [int][Math]::Floor(($count % 100) / 10)
$patch = $count % 10
$version = '{0}.{1}.{2}' -f $major, $minor, $patch

$dir = Split-Path -Parent $OutFile
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }

@"
// <auto-generated />
namespace ClipboardAtlas
{
    internal static class AppVersion
    {
        public const int CommitCount = $count;
        public const string SemVer = "$version";
        public const string Display = "v$version";
    }
}
"@ | Set-Content -Path $OutFile -Encoding UTF8

if ($PropsFile) {
    $propsDir = Split-Path -Parent $PropsFile
    if (-not (Test-Path $propsDir)) { New-Item -ItemType Directory -Path $propsDir | Out-Null }
    @"
<Project>
  <PropertyGroup>
    <Version>$version</Version>
    <AssemblyVersion>$version.0</AssemblyVersion>
    <FileVersion>$version.0</FileVersion>
    <InformationalVersion>$version+$count</InformationalVersion>
  </PropertyGroup>
</Project>
"@ | Set-Content -Path $PropsFile -Encoding UTF8
}

Write-Host "kinolincopy version $version (commits=$count)"
